### PR TITLE
Close #1: Remove instance observers upon de-allocation

### LINKED ISSUE #1: Failure to clean up observers on instances
Hi @ap,

The [Workflow](jonasbn/perl-workflow) project is running into a problem with Class::Observable as [detailed in bug report #10](https://github.com/jonasbn/perl-workflow/issues/10#issuecomment-765640659).

In short, when the object goes out of scope, it is being discarded, leaving the memory address available for allocation of a new instance. When the instance goes out of scope, Class::Observable doesn't clean up the observers on that instance however. So, when a new instance is allocated on the same address (which happened in Workflow's test suite), the observers of the previous instance magically apply to the new instance.

@jonasbn, I've reported the issue here, based on Chris's redirection to Aristotle.

Regards,

Erik.

### PR DESCRIPTION
**Pull request by ehuelsmann**
The only way for Class::Observable to know when an instance is
de-allocated, is by hooking into DESTROY.  It's better to entirely
delete the key from the hash as the chances of the entry being re-used
(i.e. an instance of the same type being allocated on exactly the same
address) is low; leaving an empty arrayref does not make sense in that
respect.

Workflow implemented something similar to this fix [as a workaround](https://github.com/jonasbn/perl-workflow/commit/b702188c1cccf3d3feaf066c59b946672164ceb2).

### CODE REVIEW

**Comment by ap** [comment]
Thank you for the patch. I have been meaning to address the issues with this module for a *very* long time. (I took a stab at it over 10 years ago but never released that work (and in retrospect I’m glad I didn’t).)

As provided, the patch fixes one of those issues, but there are several more interrelated ones. I know the bug has been avoided in Workflow.pm by dropping the dependency, so I don’t know if spending time on this is of any interest to you. If it is, can I get your feedback on my branch? Specifically the last few commits:

https://github.com/ap/Class-Observable/compare/next~3...next

If not, feel free to just close this.

**Comment by ehuelsmann** [comment]
@ap There's no problem for me to spend some time on this: as maintainers with published modules on CPAN, we never know if a module is or will be used anywhere: even if no other modules on CPAN depend on it, it could very well be used on internal projects, so there's always a good reason to *at least* document known bugs, but even better to just fix them.

That said, I looked at the first two commits (collision resistance and garbage collection) and completely agree that those are what they should be. I like how you coaxed out the issue from my PR where a class could have overloaded stringification -- which could have caused its own set of undesirable side effects.

The third commit (ithreads), I also looked at, but to be honest, I'm not quite following (I haven't done much thread-based development in Perl, which could be an obstacle there...). The point being that I don't understand the role of the registry: I see you add a reference (keyed on its address) to an invocant and I see you later remove that reference in the DESTROY function. In the mean while, you use the registry hash in the CLONE class method to copy references. so, if a reference is live when a new thread is spawned, it's copied. But: why do you need to delete all references from the original hash? Won't the refaddr function return the same address? Or can you get a reference to the same invocant in one thread with a new address in the cloned interpreter?

Anway, the first two look great. I understand what the third one is trying to do, but I lack the information to understand if it works. Feel free to provide me with pointers so I can fill the gaps in my knowledge and continue my review.

**Comment by ap** [comment]
> There's no problem for me to spend some time on this

Excellent. I’m predisposed the same way, I just didn’t want to presume.

> Or can you get a reference to the same invocant in one thread with a new address in the cloned interpreter?

That’s exactly what happens. As the documentation for the `CLONE` says (which is unfortunately difficult to find as it’s [buried in `perlmod`](https://metacpan.org/pod/distribution/perl/pod/perlmod.pod#Making-your-module-threadsafe)):

> [Perl’s] ithreads work by cloning the data tree so that no data is shared between different threads. These threads can be used by using the threads module or by doing fork() on win32 (fake fork() support). When a thread is cloned all Perl data is cloned

That is, “ithreads” (interpreter threads) are not at all what one thinks of as threads.

Now, every piece of data being copied also means all of it lives at a different memory address as well. And so the registry is used to keep ahold of every object we track, because then we can find out what address it lives at after the cloning process. By putting it under the same key its data is stored in in the property hash(es), we can find its data in the other hash(es), and we move all of it from the old key to the new key, so that everything matches up again.

(Since 5.10 there has been a better solution for this in the form of [Hash::Util::FieldHash](https://metacpan.org/pod/Hash::Util::FieldHash), where the hash has magic attached that knows that its keys pertain to objects. The magic basically does exactly the same thing as the logic from the `DESTROY` and `CLONE` methods – without needing `DESTROY` and `CLONE` methods. The problem is that it only works on 5.10+, so Class::Observable would be 5.10+-only, which I don’t like. It would be possible to use [Hash::Util::FieldHash::Compat](https://metacpan.org/pod/Hash::Util::FieldHash::Compat) but that’s much heavier than this implementation on old perls and it’s another dependency whose maintenance must be trusted. Yet another option would be to put two implementations into the module – but then the module’s interface becomes subtly different between Perl versions, i.e. the Perl version support concern can’t be hidden properly and leaks out to the user.)

Thanks for asking about all this, btw. Just explaining it caused me to realise one bug (that I missed the fact that the `delete_all_observers` method needs to delete the registry entry) and one robustness issue (that if an observable class has a `DESTROY` that fails to call ours, the entries for its instances won’t be deleted from the registry, their values will just turn from weak refs to undef when they go out of scope, so `CLONE` must check for undef values (and maybe complain, loudly(?), when it encounters them)).

**Comment by ap** [comment]
> Just explaining it caused me to realise one bug and one robustness issue

Fixed in the last version of the commit (only the last commit was affected).

**Comment by ehuelsmann** [comment]
Looking good after these adjustments. I had wondered about the possibility of stake weak references, indeed, but that issue is now supported then. If/when you merge (and release?), this can be closed.

**Comment by ap** [comment]
2.000 is on CPAN, with all the changes discussed.

**Comment by ehuelsmann** [comment]
Very nice work on the new release. Thanks!

**Pull request closed without merging**
